#!/usr/bin/env bash
# Bash script that transfer a file from our client to a server

if [ $# -lt 4 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNMAE PATH_TO_SSH_KEY";
else
    scp -o "Stricthostkeychecking=no" -i "$4" "$1" "$3@$2":~/;
fi
