#!/usr/bin/env bash
# service (init) must say that nginx is not running after debugging nginx
sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default
sudo service nginx restart
sudo pkill -o nginx
